# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdevUV',
                'doc_host': 'https://tguilment.github.io',
                'git_url': 'https://github.com/tguilment/nbdevUV',
                'lib_path': 'nbdevUV'},
  'syms': {'nbdevUV.core': {'nbdevUV.core.foo': ('core.html#foo', 'nbdevUV/core.py')}}}
